import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
		<head>
			<meta charSet="utf-8"/>
			<meta name="viewport" content="width=device-width, initial-scale=1"/>
			<title>Ocean Pulse | Revitalize Ecosystems. Reduce Carbon Footprint</title>
			<meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1'/>
			<link rel='dns-prefetch' href='../js.hsforms.net/index.html'/>
			<link rel='dns-prefetch' href='../js.hs-scripts.com/index.html'/>
			<link rel='stylesheet' id='base-theme-style-css'
						href='/css/theme3717.css?id=1ff26c07751ffdbc930c' type='text/css'
						media='all'/>
			<script type="text/javascript" src="/js/jquery/jquery.minf43b.js?ver=3.7.1"
							id="jquery-core-js"></script>
			<script type="text/javascript" src="/js/jquery/jquery-migrate.min5589.js?ver=3.4.1"
							id="jquery-migrate-js"></script>
			<link rel='shortlink' href='index.html'/>
			<link rel="alternate" type="application/json+oembed"
						href="wp-json/oembed/1.0/embedd072.json?url=https%3A%2F%2Fpachama.com%2F"/>
			<link rel="alternate" type="text/xml+oembed"
						href="wp-json/oembed/1.0/embed140d?url=https%3A%2F%2Fpachama.com%2F&amp;format=xml"/>
		</head>
		<body className={`home ${inter.className}`}>
			<main>{children}</main>
		</body>

		<Script id="base-theme-script-js" src="/js/appa823.js?id=2c21442761bd58ede18e" />

		<Script>
			{`
window.addEventListener("load", function() {
if (hbspt) {
var form_options = {
onFormReady: function(e) {
\t\t\t\t\t\t\t\t\t\t\t$('.hs-input').on('input', function() {
\t\t\t\t\t\t\t\t\t\t\tif (!this.value) {
\t\t\t\t\t\t\t\t\t\t\t$(this).closest('.hs-form-field').removeClass('has-value')
\t\t\t\t\t\t\t\t\t\t} else {
\t\t\t\t\t\t\t\t\t\t\t$(this).closest('.hs-form-field').addClass('has-value')
\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t});
\t\t\t\t\t\t\t\t\t\t},
\t\t\t\t\t\t\t\t\t\t\tonBeforeValidationInit: function() {},
\t\t\t\t\t\t\t\t\t\t\tonBeforeFormInit: function() {},
\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\thbspt.forms.create($.extend(true, form_options, {"portalId":"21158180","formId":"56d264bf-9bcb-4b41-8b5a-b0a847307ff6","submitButtonClass":"btn btn-full","validationOptions":{"grouped":true,"inputEvent":"keyup","message":"<div\\/>","messageClass":"ui red pointing below label"}}));
\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t});

				window.addEventListener("load", function() {
\t\t\t\tif (hbspt) {
\t\t\t\tvar form_options = {
\t\t\t\tonFormReady: function(e) {
\t\t\t\t$('.hs-input').on('input', function() {
\t\t\t\tif (!this.value) {
\t\t\t\t$(this).closest('.hs-form-field').removeClass('has-value')
\t\t\t} else {
\t\t\t\t$(this).closest('.hs-form-field').addClass('has-value')
\t\t\t}
\t\t\t});
\t\t\t},
\t\t\t\tonBeforeValidationInit: function() {},
\t\t\t\tonBeforeFormInit: function() {},
\t\t\t}
\t\t\t\thbspt.forms.create($.extend(true, form_options, {"portalId":"21158180","formId":"46486b0e-bb54-4953-aa2e-359e341dfe21","submitButtonClass":"btn btn-full","validationOptions":{"grouped":true,"inputEvent":"keyup","message":"<div\\/>","messageClass":"ui red pointing below label"}}));
\t\t\t}
\t\t\t});`}
		</Script>
		</html>
	);
}
